# Final, corrected Cloud Build configuration for deploying the FastAPI application
steps:
  # Step 1: Build the Docker image from backend/Dockerfile
  # The context is the root directory '.', and the Dockerfile location is specified with '-f'.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/whatsapp-bot-repo/whatsapp-bot-service:$COMMIT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - '.'

  # Step 2: Push the built image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/whatsapp-bot-repo/whatsapp-bot-service:$COMMIT_SHA']

  # Step 3: Deploy the new image version to Cloud Run
  - name: 'gcr.io/google-cloud-sdk/gcloud'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'whatsapp-bot-service'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/whatsapp-bot-repo/whatsapp-bot-service:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=whatsapp-bot-service@vortex-ai-user.iam.gserviceaccount.com'
      - '--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,TWILIO_ACCOUNT_SID=TWILIO_ACCOUNT_SID:latest,TWILIO_AUTH_TOKEN=TWILIO_AUTH_TOKEN:latest,TWILIO_PHONE_NUMBER=TWILIO_PHONE_NUMBER:latest,GOOGLE_APPLICATION_CREDENTIALS=gcp-sa-key:latest'
      - '--min-instances=0'
      - '--max-instances=2'

options:
  logging: CLOUD_LOGGING_ONLY 